!include ../../../styles/PlantUML_StyleSheet.puml

actor ユーザー as user #9EA0CA
participant "Clovaアプリ" as ca #9EA0CA
participant "クライアントデバイス" as cli #9EA0CA
participant CIC as cic #05D686

user ->> ca: デバイスの設定を変更する

  activate ca

  ca ->> cic: デバイスの設定を変更するようにリクエストする

  activate cic

    cic ->> cli: デバイスの設定を変更するように指示する\n(Settings.Updateディレクティブを送信する)

    activate cli

      cli -> cli: デバイスの設定を変更する

      cli ->> cic: デバイスの現在の設定情報をレポートする\n(Settings.Reportイベントを送信する)

    deactivate cli

  cic ->> ca: 変更された設定情報で同期するように指示する

  deactivate cic

  ca -> ca: デバイスの設定情報を更新する
  
  ca ->> user: デバイスの設定情報を提供する

deactivate ca
