!include ../../../styles/PlantUML_StyleSheet.puml

participant "Clova app" as ca #9EA0CA
participant "Client device 1" as cli1 #9EA0CA
participant "Client device 2" as cli2 #9EA0CA
participant CIC as cic #05D686

activate ca
  ca ->> cic : Request playback state of clients
deactivate ca

group Request state report

  activate cic

    cic ->> cli1 : Forward AudioPlayer.ExpectReportPlaybackState directive\n(via downchannel)
    activate cli1

    cic ->> cli2 : Forward AudioPlayer.ExpectReportPlaybackState directive\n(via downchannel)
    activate cli2

  deactivate cic

end

...After collecting playback state from clients...

group Report state

    cli2 ->> cic : Send AudioPlayer.ReportPlaybackState event\n(Reporting playback state)
    deactivate cli2
  activate cic

    cli1 ->> cic : Send AudioPlayer.ReportPlaybackState event\n(Reporting playback state)
    deactivate cli1

end

    cic -> cic : Refine collected state

group Synchronize state

    cic ->> ca : Share playback state
    activate ca

    ca -> ca : Update playback state of clients

  deactivate cic

end