!include ../../../styles/PlantUML_StyleSheet.puml

participant "Clovaアプリ" as ca #9EA0CA
participant "クライアント 1" as cli1 #9EA0CA
participant "クライアント 2" as cli2 #9EA0CA
participant CIC as cic #05D686

activate ca
  ca ->> cic : クライアントのオーディオ再生状態をリクエストする
deactivate ca

group Request state report

  activate cic

    cic ->> cli1 : AudioPlayer.ExpectReportPlaybackStateディレクティブを送信する\n(via downchannel)
    activate cli1

    cic ->> cli2 : AudioPlayer.ExpectReportPlaybackStateディレクティブを送信する\n(via downchannel)
    activate cli2

  deactivate cic

end

... クライアントから再生状態を収集した後 ...

group Report state

    cli2 ->> cic : AudioPlayer.ReportPlaybackStateイベントを送信する\n(再生状態をレポートする)
    deactivate cli2
  activate cic

    cli1 ->> cic : AudioPlayer.ReportPlaybackStateイベントを送信する\n(再生状態をレポートする)
    deactivate cli1

end

    cic -> cic : 収集された状態を整理する

group Synchronize state

    cic ->> ca : 再生状態を共有する
    activate ca

    ca -> ca : クライアントの再生状態を更新する

  deactivate cic

end