!include ../../../styles/PlantUML_StyleSheet.puml

actor ユーザー as user #9EA0CA
participant クライアント as client #9EA0CA
participant CIC as cic #05D686


user ->> client : 音楽を再生するようにリクエストする：\n「楽しい曲を再生して」

activate client
  client ->> cic : ユーザーのリクエストを送信する\n(SpeechRecognizer.Recognizeイベント)
deactivate client

activate cic
  cic -> cic : ユーザーの発話を解析する
  cic -->> client : オーディオ再生を指示する(AudioPlayer.Playディレクティブ)
deactivate cic

activate client
  client -> client : AudioPlayer.PlayディレクティブのaudioItem.streamフィールドを解析する

opt audioItem.stream.urlPlayable == false

... オーディオ再生が開始される直前まで時間が経過した後 ...

  client ->> cic : audioItem.streamフィールドの情報を使って、実際のオーディオストリームの情報をリクエストする\n(AudioPlayer.StreamRequestedイベント)
  deactivate client
  activate cic

    cic -->> client : 再生できるオーディオストリームの情報を送信する\n(AudioPlayer.StreamDeliverディレクティブ)
  deactivate cic
  activate client
    client -> client : AudioPlayer.StreamDeliverディレクティブのaudioStreamフィールドを解析する
end

client -> client : オーディオ再生を開始する
