!include ../../../styles/PlantUML_StyleSheet.puml

actor ユーザー as user #9EA0CA
participant クライアント as client #9EA0CA
participant CIC as cic #05D686
participant Clova as clova #05D686

user ->> client: 「クラシック音楽をプレイして」

activate client
  client ->> cic: Recognizeイベントを送信する\n「クラシック音楽をプレイして」
deactivate client

activate  cic
  cic ->> clova: ユーザーの音声認識をリクエストする
deactivate cic

activate clova
  clova -> clova: 音声を認識する

  clova -> clova: 意味を解析する

  clova -->> cic: 意味を解析した結果を送信する
deactivate clova

activate cic
  cic -->> client: 要請結果を指示メッセージで転送\n「案内音声,音源情報,再生指示など」
deactivate cic

activate client
  client -> client: 指示メッセージ処理
  client -->> user: 処理結果の提供
deactivate client