!include ../../../styles/PlantUML_StyleSheet.puml

participant User as user #9EA0CA
participant Client as client #9EA0CA
participant CIC as cic #05D686

user ->> client: Play classical music

activate client

  client -> client: Create a dialogue ID (A)

  alt Voice request

    client ->> cic: Sends the SpeechRecognizer.Recognize event message\n(header.dialogRequestId: A)

  else Text request

    client ->> cic: Sends the TextRecognizer.Recognize event message\n(header.dialogRequestId: A)

  end

  client -> client: Renews the latest dialogue ID

  note left: lastDialogueID: A

  ... Processing request ...

user -->> client: "Tell me the current weather"

  client -> client: Creates a dialogue ID (B)

  alt Task handled successfully

    client ->> cic: Sends the SpeechRecognizer.Recognize event message\n(header.dialogRequestId: B)

    client -> client: Renews the latest dialogue ID

    note left: lastDialogueID: B

    client -> client: Stops processing tasks related to the previous dialogue ID (A)

    client -> client: Discards all directives related to the dialogue ID (A) from the message queue

  else Cancelled sending event messages that occurred due to exceptions

    client -> client: Stops processing tasks related to the dialogue ID (A) (continued)

    note left: lastDialogueID: A

  end
