!include ../../../styles/PlantUML_StyleSheet.puml

actor User as user #9EA0CA
participant "Clova app" as app #9EA0CA
participant Client as client #9EA0CA
participant CIC as cic #05D686

alt Control audio playback through utterance

  user ->> client : Request music playback control:\n"Pause music."

  activate client
    
    client ->> cic : Send user request\n(SpeechRecognizer.Recognize event)
  
  deactivate client

  activate cic

    cic -> cic : Analyze user utterance

else Control audio playback using the client device button

  user ->> client : Press pause button

  activate client
    
    client ->> cic : Report occurrence of pause command\n(PlaybackController.PauseCommandIssued event)
  
  deactivate client

else Clova Remote control audio playback using Clova app

  user ->> app : Request to pause audio playback on the client

  activate app

    app ->> cic : Send request to pause audio playback on the client
    
  deactivate app

    cic ->> client : Request to operate as if a user has pressed the pause button\n(PlaybackController.ExpectPauseCommand directive)

  activate client

    client ->> cic : Report occurrence of pause command\n(PlaybackController.PauseCommandIssued event)

  deactivate client

end


activate cic

  cic -->> client : Direct to stop audio playback\n(PlaybackController.Pause directive)

deactivate cic

activate client

  client -> client : Pause audio playback
  client ->> cic : Report pause of audio playback\n(AudioPlayer.PlayResumed event)

deactivate client

activate cic
