!include ../../../styles/PlantUML_StyleSheet.puml

actor User as user
participant "Bluetooth device" as device #9EA0CA
participant Client as client #9EA0CA
participant "Clova" as clova #05D686

user ->> client : Requests audio playback
activate client
client ->> clova : SpeechRecognizer.Recognize\nSends an event message
deactivate client
activate clova
alt Client role == sink
  clova ->> client : DeviceControl.BtPlay\nSends a directive message

activate client

	device -> client : Receives an audio stream from the Bluetooth device
  activate device
    client -> user : Plays audio from the speaker
else Client role == source
        clova -> client : AudioPlayer.Play\nSends a directive message
        client -> device : Sends audio to the Bluetooth speaker
    device -> user : Plays audio from the Bluetooth speaker
end
  client --> clova : DeviceControl.ActionExecuted (with DeviceState) \nSends an event message
deactivate client
deactivate device
deactivate clova
