!include ../../../styles/PlantUML_StyleSheet.puml

participant Client as client #9EA0CA
participant CIC as cic #05D686
participant Clova as clova #05D686

activate client
  client ->> cic: Sends Recognize event\n"Play classic music."
deactivate client

activate  cic
  cic ->> clova: Requests user speech recognition
deactivate cic

activate clova
  clova -> clova: Recognizes speech

  clova -> clova: Analyzes semantics
  clova -->> cic: Sends semantics analysis result
deactivate clova

activate cic
  cic -->> client: Sends Speak directive\n"Here is classic music."

activate client
  client -> client: Outputs voice
  cic -->> client: Sends RenderText directive\n"Here is classic music."
  client -> client: Displays text on screen
  cic -->> client: Sends Play directive\nincluding music information on "Vivaldi: Seasons Spring"
deactivate cic
  client -> client: Plays music

  client ->> cic: Sends PlayStarted event\nSends the playback state of client

deactivate client

activate cic

cic ->> clova: Sends the playback state of the client

activate clova
