!include ../../../styles/PlantUML_StyleSheet.puml

participant "Bluetooth device" as device #9EA0CA
participant Client as client #9EA0CA
participant "Clova" as clova #05D686

activate device
activate client
hnote over device, clova : Request to disable a Bluetooth device
activate clova
 alt Specific device assigned == Yes
  clova -> client : DeviceControl.BtDisconnect (with payload)\nSend a directive message
 else Specific device assigned == No
    clova -> client : DeviceControl.BtDisconnect (without payload)\nSend a directive message
end
  client -> device : Disconnect
deactivate device
  client --> clova : DeviceControl.ActionExecuted (with DeviceState)\nSend an event message
hnote over device, clova : Share the result of disabling the Bluetooth device
deactivate client
deactivate device
deactivate clova
