!include ../../../styles/PlantUML_StyleSheet.puml

participant "Client without GUI" as device #9EA0CA
participant "Client with GUI" as app #9EA0CA
participant "NAVER authorization server" as nauth #05D686
participant "Clova authorization server" as cauth #05D686
participant CIC as cic #05D686

activate app
  app -> app: Logs in to NAVER

  app ->> nauth: Sends NAVER account information

  activate nauth
    nauth -->> app: Sends the NAVER account\naccess token
  deactivate nauth

  app ->> cauth: Requests the authorization code (Sends the next information)\l- NAVER account access token\l- Client credentials (CLOVA_OAUTH_CLIENT_ID)

activate cauth

deactivate app

alt "Status of Terms and Conditions agreement" == "Agreed"
    cauth -->> app: Sends the authorization code (200 OK)
    activate app
    deactivate app
else Status of Terms and Conditions agreement == "Not agreed"
  cauth -->> app: Sends the authorization, redirect_uri\l(451 Unavailable For Legal Reasons)
  activate app
    app -> app: Moves to the Terms and Conditions page (redirect_uri)
    app ->> cauth: Sends the result of user agreement to the Terms and Conditions (submit)
    cauth -->> app: Sends the result (302 Found)\l- Success: clova://agreement-success\l- Failure: clova://agreement-failure
  deactivate cauth
end

alt "Client type" == "Client with GUI"
  app ->> cauth: Requests the Clova access token (Send the next information)\l- NAVER account access token\l- Client credentials\l  (CLOVA_OAUTH_CLIENT_ID, CLOVA_OAUTH_CLIENT_SECRET)

  activate cauth
    cauth -->> app: Sends the Clova access token
  deactivate cauth

  app ->> cic: Starts connection to CIC using the Clova access token
  activate cic
  deactivate cic

else "Client type" == "Client without GUI"
  app ->> device: Sends the authorization code
  deactivate app

  activate device
    device ->> cauth: Requests the Clova access token (Sends the next information)\l- NAVER account access token\l- Client credentials\l  (CLOVA_OAUTH_CLIENT_ID, CLOVA_OAUTH_CLIENT_SECRET)

    activate cauth
        cauth -->> device: Sends the Clova access token
    deactivate cauth

    device ->> cic: Starts connection to CIC using the Clova access token

    activate cic
  end
