!include ../../../styles/PlantUML_StyleSheet.puml

participant "Bluetooth device" as device #9EA0CA
participant Client as client #9EA0CA
participant "Clova" as clova #05D686
actor User as user #9EA0
activate device
device -> client: Advertising
...
user ->> clova : Requests a Bluetooth device connection
activate clova
  clova -> client : Sends the DeviceControl.BtStartPairing directive

activate client
  client -> client : Scans
  client --> clova : Sends the DeviceControl.ActionExecuted event\n(with DeviceState)
  hnote over client, device : Found a Bluetooth device
deactivate client

 alt Specific device assigned == Yes
	clova -> client : Sends the DeviceControl.BtConnect directive\n(with payload)

	activate client
 else Specific device assigned == No
    clova -> client : Sends the DeviceControl.BtConnect directive\n(without payload)
end

  client -> device : Requests a connection
  client --> clova : Sends the DeviceControl.ActionExecuted event\n(with DeviceState)

	deactivate client
  alt PIN code required == Yes
	device ->> client : Requests a PIN code

	activate client
	client -> clova : Sends the DeviceControl.BtRequestForPINCode event
    hnote over clova, user #05D686 : Requests a PIN code and handles the input

    alt Decide to cancel code input == Yes
		client -> clova : Sends the DeviceControl.BtRequestToCancelPINCode event
		hnote over clova, user #05D686 : Handles the cancellation of PIN code request
    else
 		clova -> client : Sends the DeviceControl.BtConnectByPINCode directive
	end
  end
    client -> device : Connects using a PIN code
    client -> clova : Sends the DeviceControl.ActionExecuted event

	deactivate client
	device -->> client : Returns the connection result
 deactivate device

  clova -> user : Notifies of the connection result

deactivate clova
