!include ../../../styles/PlantUML_StyleSheet.puml

actor User as user #9EA0CA
participant "Clova app" as ca #9EA0CA
participant "Client device" as cli #9EA0CA
participant CIC as cic #05D686

user ->> ca: Checks the current device settings

activate ca

  ca ->> cic: Requests to synchronize the current device settings

  activate cic

    cic ->> cli: Requests the current device settings information\n(Sends Settings.Report directive)

    activate cli

      cli ->> cic: Reports the current settings information of the device\n(Sends Settings.Report event)

    deactivate cli

    cic ->> ca: Directs to synchronize the current device settings

  deactivate cic

  ca -> ca: Refreshes device settings

  ca ->> user: Provides device settings

deactivate ca
