!include ../../../styles/PlantUML_StyleSheet.puml

actor User as user #9EA0CA
participant "Clova app" as ca #9EA0CA
participant "Client device" as cli #9EA0CA
participant CIC as cic #05D686

user ->> ca: Changes device settings

  activate ca

  ca ->> cic: Requests to change the device settings

  activate cic

    cic ->> cli: Directs to change the device settings\n(Sends Settings.Update directive)

    activate cli

      cli -> cli: Changes device settings

      cli ->> cic: Reports the current settings information of the device\n(Sends Settings.Report event)

    deactivate cli

  cic ->> ca: Directs to synchronize to the changed settings

  deactivate cic

  ca -> ca: Refreshes device settings

  ca ->> user: Provides device settings

deactivate ca
