!include ../../../styles/PlantUML_StyleSheet.puml

actor User as user #9EA0CA
participant Client as client #9EA0CA
participant CIC as cic #05D686


user ->> client : Requests to add an alarm:\n"Set an alarm for 9 PM today."

activate client
  client ->> cic : Sends user request\n(SpeechRecognizer.Recognize event)
deactivate client

activate cic
  cic -> cic : Analyzes user utterance
  cic -->> client : Sends Alerts.SetAlert directive
deactivate cic

activate client
  client -> client : Adds an alarm to client device

alt Result of adding an alarm == Failed to add

  client ->> cic : Sends Alerts.SetAlertFailed event
  deactivate client
  activate cic

    cic -->> client : Sends SpeechSynthesizer.Speak directive\n("Could not set the alarm.")
  deactivate cic
  activate client
    client -->> user : Sends result of adding an alarm

else Result of adding an alarm == Success

  client ->> cic : Sends Alerts.SetAlertSucceeded event

deactivate client

activate cic
  cic -> cic : Adds user alarm
  cic -->> client : Sends SpeechSynthesizer.Speak directive\n("The alarm is set.")
activate client
  cic -->> client : Sends Actiontimer, Alarm, Reminder, and Timer templates\n(Clova.RenderTemplate directive)
deactivate cic

  client -> client : Outputs voice and display added alarm details
  client -->> user : Sends result of adding an alarm

  end
