!include ../../../styles/PlantUML_StyleSheet.puml

participant "Bluetooth device" as device #9EA0CA
participant Client as client #9EA0CA
participant "Clova" as clova #05D686

activate clova
activate device
hnote over device, clova : Requests a Bluetooth device connection
 alt Specific device assigned == Yes
	clova ->> client : DeviceControl.BtConnect (with payload)\nSends a directive message

	activate client
 else Specific device assigned == No
    clova ->> client : DeviceControl.BtConnect (without payload)\nSends a directive message
end

  client ->> device : Requests connection
  client -->> clova : DeviceControl.ActionExecuted (with DeviceState)\nSends an event message

	deactivate client
opt If the device to connect requests a PIN code
	device ->> client : Requests a PIN code

	activate client

  group "Enter the user's PIN code"
    client ->> clova : DeviceControl.BtRequestForPINCode\nSends an event message
    hnote over client, clova : Handles the user's PIN code input
    clova ->> client : DeviceControl.BtConnectByPINCode\nSends a directive message
  end
  client ->> device : Requests a connection using PIN code
  client ->> clova: DeviceControl.ActionExecuted\nSends an event message
	device -->> client : Accepts the device connection
  client ->> clova : DeviceControl.ReportState\nSends an event message
deactivate client
end
hnote over device, clova : Shares the connection result
