!include ../../../styles/PlantUML_StyleSheet.puml

actor ユーザー as user #9EA0CA
participant クライアント as client #9EA0CA
participant CIC as cic #05D686

user ->> client : アラームの設定をリクエストする：\n「今日の午後9時にアラームを設定して」

activate client
  client ->> cic : ユーザーのリクエストを送信する\n(SpeechRecognizer.Recognizeイベント)
deactivate client

activate cic
  cic -> cic : ユーザーの発話を解析する
  cic -->> client : Alerts.SetAlertディレクティブを送信する
deactivate cic

activate client
  client -> client : クライアントデバイスにアラームを設定する

opt アラーム設定結果 == 設定失敗

  client ->> cic : Alerts.SetAlertFailedイベントを送信する
  deactivate client
  activate cic

    cic -->> client : SpeechSynthesizer.Speakディレクティブを送信する\n(「アラームを設定できませんでした」)

  deactivate cic
  activate client
    client -->> user : アラームの設定結果を送信する

else アラーム設定結果 == 設定成功

  client ->> cic : Alerts.SetAlertSucceededイベントを送信する

deactivate client

activate cic
  cic -> cic : ユーザーのアラームを設定する
  cic -->> client : SpeechSynthesizer.Speakディレクティブを送信する\n(「アラームが設定されました」)

activate client
  cic -->> client : Actiontimer、Alarm、Reminder、Timerテンプレートを送信する\n(Clova.RenderTemplateディレクティブ)
deactivate cic

  client -> client : 音声出力および設定されたアラームの内容を表示する
  client -->> user : アラームの設定結果を送信する

...

  client -> client : アラームが開始される
  client ->> cic : アラームの開始を報告する\n(Alerts.AlertStartedイベント、\lAlert.AlertsStateのactivateAlertsフィールドは必須)

  activate cic
  deactivate cic

  user ->> client : アラームの停止をリクエストする(発話または物理ボタン)

  alt アラーム停止リクエストのタイプ == ユーザーの発話

    client ->> cic : アラーム停止リクエストを送信する\n(SpeechRecognizer.Recognizeイベント)

  activate cic

  else アラーム停止リクエストのタイプ == 物理ボタン

    client ->> cic : アラーム停止リクエストを送信する\n(Alerts.RequestAlertStopイベント)

  end

  cic -->> client : Alerts.StopAlertディレクティブを送信する

  deactivate cic

  client ->> cic : アラームの停止結果を報告する\n(Alerts.AlertStoppedイベント)

  activate cic

    opt アラームの繰り返し == はい

      cic -->> client : アラームの次の繰り返しを送信する\n(Alerts.SetAlertディレクティブ)

    end

    opt アラームタイプ == アクションタイマー

      cic -->> client : ユーザーが予約した動作を実行するディレクティブを送信する

  deactivate cic
      client -> client : 予約された動作を実行する

    end

  deactivate client
  deactivate cic

  end
