!include ../../../styles/PlantUML_StyleSheet.puml

actor User as user #9EA0CA
participant "Clova app" as ca #9EA0CA
participant "Client device" as cli #9EA0CA
participant CIC as cic #05D686

user ->> ca: Change device settings

  activate ca

  ca ->> cic: Request to change the device settings

  activate cic

    cic ->> cli: Direct to change the device settings\n(Send Settings.Update directive)

    activate cli

      cli -> cli: Change device settings

      cli ->> cic: Report the current settings information of the device\n(Send Settings.Report event)

    deactivate cli

  cic ->> ca: Direct to synchronize to the changed settings

  deactivate cic

  ca -> ca: Refresh device settings
  
  ca ->> user: Provide device settings

deactivate ca
