!include ../../../styles/PlantUML_StyleSheet.puml

actor User as user #9EA0CA
participant Client as client #9EA0CA
participant CIC as cic #05D686


user ->> client : Request music playback:\n"Play some upbeat music."

activate client
  client ->> cic : Send user request\n(SpeechRecognizer.Recognize event)
deactivate client

activate cic
  cic -> cic : Analyze user utterance
  cic -->> client : Direct audio playback (AudioPlayer.Play directive)
deactivate cic

activate client
  client -> client : Analyze audioItem.stream field of AudioPlayer.Play directive

opt audioItem.stream.urlPlayable == false

... Time elapses until right before starting audio playback, ...

  client ->> cic : Request actual audio information to the audioItem.stream field\n(AudioPlayer.StreamRequested event)
  deactivate client
  activate cic

    cic -->> client : Send playable audio information\n(AudioPlayer.StreamDeliver directive)
  deactivate cic
  activate client
    client -> client : Analyze audioStream field of AudioPlayer.StreamDeliver directive
end

client -> client : Start audio playback

