!include ../../../styles/PlantUML_StyleSheet.puml

actor User as user #9EA0CA
participant Client as client #9EA0CA
participant CIC as cic #05D686

activate client

  client -> client : Start audio playback
  client ->> cic : Report start of audio playback (AudioPlayer.PlayStarted event)

  activate cic
  deactivate cic

  opt progressReport.progressReportDelayInMilliseconds != null

    ... After starting audio playback and passing a specific duration ...

    client ->> cic : Report progress of audio playback (AudioPlayer.ProgressReportDelayPassed event)

    activate cic
    deactivate cic

  end

  opt progressReport.progressReportIntervalInMilliseconds != null

    loop Until audio playback stops,

      ... After passing a specific time interval, ...

      client ->> cic : Report progress of audio playback (AudioPlayer.ProgressReportIntervalPassed event)

      activate cic
      deactivate cic

    end

  end

  opt progressReport.progressReportPositionInMilliseconds != null

    ... After passing a specific point in playback ...

    client ->> cic : Report progress of audio playback (AudioPlayer.ProgressReportPositionPassed event)

    activate cic
    deactivate cic

  end

  ... After completing audio playback ...

  client ->> cic : Report completion of audio playback (AudioPlayer.PlayFinished event)

deactivate client
activate cic
deactivate cic
