!include ../../../styles/PlantUML_StyleSheet.puml

participant Client as client #9EA0CA
participant "Clova" as clova #05D686

hnote over client, clova : Request to delete a Bluetooth device
activate clova
  clova ->> client : DeviceControl.BtDelete (with payload)\nSend a directive message
  activate client
  client -->> clova : DeviceControl.ActionExecuted (with DeviceState)\nSend an event message
  deactivate client
hnote over client, clova : Share the result of deleting a device